stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ if eq(environment.name, parameters.build) }}:
      - stage: ${{ format('Build_{0}', environment.name) }}
        displayName: ${{ format('Build {0}', environment.name) }}
        ${{ if and(environment.envPool, ne(convertToJson(environment.envPool), '{}')) }}:
          pool: ${{ environment.envPool }}
        ${{ if and(ne(and(environment.envPool, ne(convertToJson(environment.envPool), '{}')), true), '{}'), and(parameters.pool, ne(convertToJson(parameters.pool), '{}')) }}:
          pool: ${{ parameters.pool }}
        dependsOn: ${{ parameters.dependsOn }}
        jobs:
          - template: build_jobs.yml
            parameters:
              name: ${{ environment.name }}
              env: ${{ environment.env }}
              buildParameters: ${{ parameters.buildParameters }}
              sources: ${{ parameters.sources }}
              projectSrc: ${{ coalesce(parameters.projectSrc, 'src') }}
              preBuildScript: ${{ parameters.preBuildScript }}
              artifactNamePrefix: ${{ parameters.artifactNamePrefix }}
              useDotNetSDK: ${{ parameters.useDotNetSDK }}
